/* SPDX-License-Identifier: GPL-2.0+ */
/*
 * Copyright 2019 NXP
 */

#ifndef __MODULINE_DISPLAY_H
#define __MODULINE_DISPLAY_H

#include <linux/sizes.h>
#include <asm/arch/imx-regs.h>

#define CONFIG_FDTADDR		0x43000000

#define SOC_PREFIX		"imx8m"
#define SOC_FAMILY		"imx8mp"

#ifdef CONFIG_SPL_BUILD
#define CONFIG_ENABLE_DDR_TRAINING_DEBUG
#define CONFIG_USBD_HS

#define CONFIG_MALLOC_F_ADDR	0x95b0000

#define CONFIG_SYS_SPL_MALLOC_START	0x42200000
#define CONFIG_SYS_SPL_MALLOC_SIZE	SZ_512K

#ifndef CONFIG_SPL_BSS_MAX_SIZE
#define CONFIG_SPL_BSS_MAX_SIZE		SZ_2K
#endif

#if CONFIG_IS_ENABLED(USB_SUPPORT)
#define CONFIG_SYS_USB_FAT_BOOT_PARTITION	1
#define CONFIG_SPL_FS_LOAD_PAYLOAD_NAME		"u-boot"
#endif

#endif /* CONFIG_SPL_BUILD */

/* Link Definitions */

#define CFG_SYS_SDRAM_BASE           0x40000000

#define CFG_SYS_INIT_RAM_ADDR        CFG_SYS_SDRAM_BASE
#define CFG_SYS_INIT_RAM_SIZE        SZ_2M
#define CONFIG_SYS_INIT_SP_OFFSET \
	(CFG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)
#define CONFIG_SYS_INIT_SP_ADDR \
	(CFG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)

#ifdef CONFIG_ARMV8_SEC_FIRMWARE_SUPPORT
#define CONFIG_SYS_MEM_RESERVE_SECURE	0
#endif

#define PHYS_SDRAM                   CFG_SYS_SDRAM_BASE
#define PHYS_SDRAM_SIZE		     SZ_2G /* 2GB DDR */

#ifdef CONFIG_DEBUG_UART
#define CONFIG_MXC_UART_BASE		CONFIG_DEBUG_UART_BASE
#endif

#define CONFIG_SYS_FSL_USDHC_NUM	3
#define CONFIG_SYS_FLS_ESDHC_ADDR	0

#endif
